dataset_name: "pbmc_unsorted_3k_multiome_bam"
sample_file: "examples/pbmc_unsorted_3k_multiome_bam/sample_sheet.csv"
cell_annots: "examples/pbmc_unsorted_3k_multiome_bam/annots.csv"
target: "utrome_hg38_v1"

bx_whitelist: "extdata/bxs/gex_737K-arc-v1.txt"
tech: "10xv3"
strand: "--fr-stranded"

min_umis: 500
