---
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    df_print: paged
    theme: cosmo
    toc: TRUE
    toc_depth: 2
    toc_float: true
---

```{r echo=FALSE}
title_str <- sprintf("UMI Counts Distribution - %s", snakemake@wildcards$sample_id)
author_str <- sprintf("scUTRquant v%s", snakemake@params$sq_version)
```

---
title: `r title_str`
author: `r author_str`
---

# Libraries
```{r libs, message=FALSE, warning=FALSE}
library(Matrix)
library(dplyr)
library(ggplot2)
library(readr)
library(magrittr)
```

# Load Data
```{r load_data}
cts_tx_bc <- readMM(snakemake@input$mtx) %>%
  as("CsparseMatrix") %>%
  `dimnames<-`(list(
    cell_bx=read_lines(snakemake@input$bxs),
    transcript_name=read_lines(snakemake@input$txs)
  )) %>%
  t %>%
  { .[, colSums(.) > 0] } # filter empty barcodes
```

# Plot UMI Count Distribution

Here we plot the empirical distribution of UMI counts per cell barcode and indicate 
the specified minimum UMI count (`r snakemake@params$min_umis`) in blue.

```{r plt_umis_by_barcode}
colSums(cts_tx_bc) %>%
  sort(decreasing=TRUE) %>%
  { tibble(x=seq_along(.), y=.) } %>%
  ggplot(aes(x,y)) +
  geom_line() +
  geom_hline(yintercept=as.integer(snakemake@params$min_umis),
	     color='blue', linetype='dashed') +
  scale_x_log10(expand=c(0,0,0.05,0)) +
  scale_y_log10(expand=c(0,0,0.05,0)) +
  labs(x="Cell Barcode Rank", y="UMI Count", title=snakemake@wildcards$sample_id) +
  theme_bw()
```

---

# Runtime Details
## Session Info
<details>
```{r sesh_info, echo=FALSE}
sessionInfo()
```
</details>

## Conda Environment
<details>
```{bash conda_info, comment="", echo=FALSE}
if ! command -v conda &> /dev/null
then
  echo "Conda not detected."
elif [ -z "${CONDA_PREFIX}" ]
then
  echo "No active Conda environment."
else
  echo "## Conda Environment YAML"
  PREFIX=$(dirname $(dirname $(which R)))
  conda env export -p $PREFIX
fi
```
</details>
